/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vertx.communication;

import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.spi.cluster.hazelcast.HazelcastClusterManager;

import vertx.communication.sender.SenderVerticle;
import vertx.communication.receiver.ReceiverVerticle;

public class App {

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        HazelcastClusterManager mgr = new HazelcastClusterManager();
        VertxOptions options = new VertxOptions().setClusterManager(mgr);
        Vertx.clusteredVertx(options, res -> {
            if (res.succeeded()) {
                Vertx vertx = res.result();
                vertx.deployVerticle(new SenderVerticle(), deploy_res -> {
                    if (deploy_res.succeeded()) {
                        System.out.println("Deployment id is: " + deploy_res.result());
                    } else {
                        System.out.println("Deployment failed!");
                        System.out.println(res.toString());
                    }
                });
            }
            else {
                System.out.println("Failed to create clustered vertx");
            }
        });
    }
}
